INSERT INTO tools (name, available) VALUES ('Drill', true);
INSERT INTO tools (name, available) VALUES ('Hammer', true);
INSERT INTO tools (name, available) VALUES ('Saw', true);
INSERT INTO tools (name, available) VALUES ('Hacksaw', true);
INSERT INTO tools (name, available) VALUES ('Monkeywrench', true);
INSERT INTO tools (name, available) VALUES ('Hatchet', true);
INSERT INTO tools (name, available) VALUES ('Pliers', true);
INSERT INTO tools (name, available) VALUES ('Chainsaw', true);
INSERT INTO tools (name, available) VALUES ('Anvil', true);
INSERT INTO tools (name, available) VALUES ('Soldering iron', true);
INSERT INTO tools (name, available) VALUES ('Circular saw', true);
INSERT INTO tools (name, available) VALUES ('Workbench', true);
INSERT INTO tools (name, available) VALUES ('Tape measure', true);
INSERT INTO tools (name, available) VALUES ('Ladder', true);